name: Workflow testing

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  issues:
    types: [opened, edited]


jobs:
  experimental-great:
    env: 
      MY_ENV: "John Doe"
    runs-on: ubuntu latest
    steps:
      - name: Greet the User
        run: echo "Hello world!"
      - name: Show directory before checkout
        run: ls -1
      - name: Checkout our code
        uses: actions/checkout@v2
      - name: Show directory after checkout
        run: ls -1
      - name: Show env vars
        run: 
          echo "Hello $MY_ENV"
          echo "Hello $GITHUB_ACTOR
          
